@extends('layouts.store')
@section('content')
@if($query === '')
<section class="hero mb-4"><div class="row align-items-center"><div class="col-12 col-lg-7"><span class="chip mb-3"><i class="bi bi-stars"></i> Nuevos productos cada semana</span><h1 class="display-5 mt-2">Lo que buscas,<br>al <span class="resaltado">mejor precio</span></h1><p class="lead text-white-50 mb-4">Productos seleccionados con envío a todo México y pago 100% seguro.</p><form class="hero-buscador d-flex mb-4" action="{{ route('tienda.index') }}" method="get" style="max-width:460px"><input type="search" name="q" class="form-control" placeholder="Busca tu próximo favorito…"><button class="btn btn-brand" style="box-shadow:none"><i class="bi bi-search"></i></button></form><div class="d-flex flex-wrap gap-2"><span class="chip"><i class="bi bi-truck"></i> Envío nacional</span><span class="chip"><i class="bi bi-shield-check"></i> Pago seguro</span><span class="chip"><i class="bi bi-whatsapp"></i> Atención personal</span></div></div><div class="col-lg-5 d-none d-lg-flex justify-content-center"><i class="bi bi-bag-heart" style="font-size:11rem;opacity:.25"></i></div></div></section>
<div class="row g-3 mb-5"><div class="col-12 col-md-4"><div class="beneficio"><i class="bi bi-truck"></i><div><strong>Envío a todo México</strong><small>Recibe en la puerta de tu casa</small></div></div></div><div class="col-12 col-md-4"><div class="beneficio"><i class="bi bi-shield-lock"></i><div><strong>Pagos protegidos</strong><small>Tarjeta, OXXO, PayPal y más</small></div></div></div><div class="col-12 col-md-4"><div class="beneficio"><i class="bi bi-chat-heart"></i><div><strong>Atención real</strong><small>Te acompañamos por WhatsApp</small></div></div></div></div>
<h1 class="titulo-seccion h4 mb-4">Catálogo</h1>
@else
<form class="d-md-none mb-3" action="{{ route('tienda.index') }}" method="get"><input type="search" name="q" class="form-control" placeholder="Buscar productos…" value="{{ $query }}"></form><p class="text-muted mb-4">Resultados para "<strong>{{ $query }}</strong>" ({{ $products->count() }}) · <a href="{{ route('tienda.index') }}">ver todo el catálogo</a></p>
@endif
@if($products->isEmpty())<div class="text-center py-5 text-muted"><i class="bi bi-box-seam display-1"></i><p class="mt-3 fs-5">No encontramos productos{{ $query ? ' para tu búsqueda' : ' disponibles aún' }}.</p>@if($query)<a href="{{ route('tienda.index') }}" class="btn btn-brand">Ver todo el catálogo</a>@endif</div>@endif
<div class="row g-3 g-md-4 mt-1">@foreach($products as $product)<div class="col-6 col-md-4 col-lg-3"><a href="{{ route('producto.show', $product) }}" class="text-decoration-none"><div class="card-producto"><div class="marco-img">@if($product->creado_en->gt(now()->subDays(14)))<span class="badge-nuevo">NUEVO</span>@endif<img src="{{ $product->imageUrl() }}" alt="{{ $product->nombre }}" loading="lazy"></div><div class="p-3"><p class="nombre-producto mb-2">{{ str($product->nombre)->limit(80) }}</p><div class="d-flex justify-content-between align-items-center"><span class="precio">${{ number_format($product->precioFinal(), 2) }} <small>{{ $currency }}</small></span><span class="btn btn-brand btn-sm" style="padding:.35rem .7rem"><i class="bi bi-bag-plus"></i></span></div></div></div></a></div>@endforeach</div>
@endsection
