<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title ?? 'Administración' }} - {{ $storeName }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>body{background:#f4f6f9}.sidebar{min-height:100vh;background:#1e2a38}.sidebar .nav-link{color:#b8c4d0;border-radius:.4rem;margin-bottom:.15rem}.sidebar .nav-link:hover,.sidebar .nav-link.active{color:#fff;background:#2e4156}.card{border:0;box-shadow:0 1px 4px rgba(0,0,0,.07)}</style>
</head>
<body><div class="container-fluid"><div class="row"><nav class="col-12 col-md-3 col-lg-2 sidebar p-3"><a href="{{ route('admin.dashboard') }}" class="text-white text-decoration-none fs-5 fw-bold d-block mb-3"><i class="bi bi-box-seam"></i> {{ $storeName }}</a><ul class="nav nav-pills flex-column"><li><a class="nav-link {{ request()->routeIs('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}"><i class="bi bi-speedometer2 me-2"></i>Dashboard</a></li><li><a class="nav-link {{ request()->routeIs('admin.productos.*') ? 'active' : '' }}" href="{{ route('admin.productos.index') }}"><i class="bi bi-grid me-2"></i>Productos</a></li><li><a class="nav-link {{ request()->routeIs('admin.importar.*') ? 'active' : '' }}" href="{{ route('admin.importar.create') }}"><i class="bi bi-cloud-download me-2"></i>Importar</a></li><li><a class="nav-link {{ request()->routeIs('admin.pedidos.*') ? 'active' : '' }}" href="{{ route('admin.pedidos.index') }}"><i class="bi bi-receipt me-2"></i>Pedidos</a></li><li><a class="nav-link {{ request()->routeIs('admin.configuracion.*') ? 'active' : '' }}" href="{{ route('admin.configuracion.edit') }}"><i class="bi bi-gear me-2"></i>Configuración</a></li><li class="mt-3 border-top pt-2"><a class="nav-link" href="{{ route('tienda.index') }}" target="_blank"><i class="bi bi-shop me-2"></i>Ver tienda</a></li><li><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="nav-link border-0 bg-transparent w-100 text-start"><i class="bi bi-box-arrow-right me-2"></i>Salir</button></form></li></ul></nav><main class="col-12 col-md-9 col-lg-10 p-4"><div class="d-flex justify-content-between align-items-center gap-3 mb-4"><h1 class="h3 mb-0">{{ $title ?? '' }}</h1><span class="small text-muted d-none d-md-inline">{{ auth()->user()->nombre }}</span></div>@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @yield('content')</main></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>@stack('scripts')</body>
</html>
